language: node_js
os: linux
dist: bionic
node_js:
  - lts/*
install:
  - yarn install
jobs:
  include:
    # 测试构建项目
    - stage: test-build
      name: "Test Build Process"
      script: yarn run build

    # 部署 master 分支
    - stage: deploy
      name: "Deploy Demo"
      script: yarn run build
      deploy:
        provider: pages
        cleanup: false
        local_dir: dist
        token: $Github_Token
        fqdn: dev.nenuyouth.com
        edge: true
        strategy: git

stages:
  - name: test-build
    if: branch != master
  - name: deploy
    if: branch = master
